---
title: "PBK model results"
author: "Chrysanthi Pachoulide"
editor: visual
toc: true
format: 
  html:
    code-fold: true
    fig-margin: 1.0
    embed-resources: true
    self-contained-math: true
  pdf:
    knitr:
      opts_chunk:
        screenshot.force: true
    documentclass: report
    geometry: 
     - margin = 1in
     - a4paper    
    fig-width: 6.5
    fig-height: 4.5
    fig-align: center
params:
  Lifestage: "Yes"  
  Population: "Yes"  
  Test_study: "dummy"
---

```{r}
#| label: params-check
#| echo: false

message("Lifestage setting: ", params$Lifestage)
message("Population mode: ", params$Population)
message("Study: ", params$Test_study)
```

```{r}
#| label: load-pakages
#| code-summary: "Packages"
#| message: false
#| include: false

  library(here)
  library(tidyverse)
  library(glue)
  library(patchwork) 
  library(DT)
  library(plotly)
  library(tinytex)
  library(knitr)
  library(kableExtra)
  library(webshot2)
  library(showtext)
  font_add(family = "Garamond", regular = "GARA.TTF")
  showtext_auto()
  
  if (params$Population == "Yes") {
  load(here("Output", "Pers.POST.RUN_RESULTS.RData"))
  load(here("Output", "Pop.POST.RUN_RESULTS.RData"))
  } else {
  load(here("Output", "Pers.POST.RUN_RESULTS.RData"))
    }

```

# PBK Results summary

```{r}
#| label: Summary
#| echo: false

  if (params$Population == "Yes") {
  Data_summary <- do.call(rbind, lapply(Pers.POST.RUN_RESULTS, function(x) x$ANALYSED_data))
  } else {
  Data_summary <- Pers.POST.RUN_RESULTS$ANALYSED_data
  }

if (knitr::is_html_output()) {

  datatable(Data_summary, 
            options = list(pageLength = 10, 
                           scrollX = TRUE, 
                           scrollY = "50vh",
                           scrollCollapse = TRUE))
  } else {
  kable(Data_summary, 
        format = "latex",     
        booktabs = TRUE,
        caption = "Summary Table") %>%    # Center-align columns
    kable_styling(
      latex_options = c("striped", "hold_position", "scale_down"),  # Critical for fitting
      font_size = 8,  # Reduce font size if needed
      full_width = FALSE  # Prevents overflows
    ) %>%
    kableExtra::landscape()  
}

```

# Plots

```{r}
#| label: Histograms of variables
#| echo: false

if (params$Population == "Yes") {
  if (knitr::is_html_output()) {
    ggplotly(Pop.POST.RUN_RESULTS[[1]])
  } else {
    Pop.POST.RUN_RESULTS[[1]]  
  }
}


```

```{r}
#| label: Exposure vs CP predicted
#| echo: false

if (params$Population == "Yes") {
  if (knitr::is_html_output()) {
    ggplotly(Pop.POST.RUN_RESULTS[[2]])
  } else {
    Pop.POST.RUN_RESULTS[[2]]  
  }
}

```

```{r}
#| label: Age vs CP predicted
#| echo: false

if (params$Population == "Yes") {
  if (knitr::is_html_output()) {
    ggplotly(Pop.POST.RUN_RESULTS[[3]])
  } else {
    Pop.POST.RUN_RESULTS[[3]]  # Directly print the ggplot object
  }
}


```

```{r}
#| label: GFR vs CP predicted
#| echo: false

if (params$Population == "Yes") {
  if (knitr::is_html_output()) {
    ggplotly(Pop.POST.RUN_RESULTS[[4]])
  } else {
    Pop.POST.RUN_RESULTS[[4]]  
  }
}


```

```{r}
#| label: Exposure vs HL predicted
#| echo: false

if (params$Population == "Yes") {
  if (knitr::is_html_output()) {
    ggplotly(Pop.POST.RUN_RESULTS[[5]])
  } else {
    Pop.POST.RUN_RESULTS[[5]]  
  }
}


```

```{r}
#| label: Age vs HL predicted
#| echo: false

if (params$Population == "Yes") {
  if (knitr::is_html_output()) {
    ggplotly(Pop.POST.RUN_RESULTS[[6]])
  } else {
    Pop.POST.RUN_RESULTS[[6]]  
  }
}


```

```{r}
#| label: GFR vs HL predicted
#| echo: false

if (params$Population == "Yes") {
  if (knitr::is_html_output()) {
    ggplotly(Pop.POST.RUN_RESULTS[[7]])
  } else {
    Pop.POST.RUN_RESULTS[[7]]  
  }
}


```

```{r}
#| label: Observed vs predicted CP
#| echo: false

if (params$Population == "Yes" && 
    !is.character(Pop.POST.RUN_RESULTS[[8]])) {
  if (knitr::is_html_output()) {
    ggplotly(Pop.POST.RUN_RESULTS[[8]])
  } else {
    Pop.POST.RUN_RESULTS[[8]] 
  }
}


```

```{r}
#| label: Observed vs predicted HL
#| echo: false

if (params$Population == "Yes" && 
    !is.character(Pop.POST.RUN_RESULTS[[9]])) {
  if (knitr::is_html_output()) {
    ggplotly(Pop.POST.RUN_RESULTS[[9]])
  } else {
    Pop.POST.RUN_RESULTS[[9]]  
  }
}

```

```{r}
#| label: Violin plot HL
#| echo: false

if (params$Population == "Yes") {
  if (knitr::is_html_output()) {
    ggplotly(Pop.POST.RUN_RESULTS[[10]])
  } else {
    Pop.POST.RUN_RESULTS[[10]]  
  }
}

```

```{r}
#| label: MB
#| echo: false

if (params$Population == "No") {
  if (knitr::is_html_output()) {
    ggplotly(Pers.POST.RUN_RESULTS$OUT_Plots[[1]])
  } else{
    Pers.POST.RUN_RESULTS$OUT_Plots[[1]]
  }
}

```

```{r}
#| label: Corg
#| echo: false

if (params$Population == "No") {
  if (knitr::is_html_output()) {
    ggplotly(Pers.POST.RUN_RESULTS$OUT_Plots[[2]])
  } else{
    Pers.POST.RUN_RESULTS$OUT_Plots[[2]]
  }
}


```

```{r}
#| label: HL
#| echo: false

if (params$Population == "No") {
  if (knitr::is_html_output()) {
    ggplotly(Pers.POST.RUN_RESULTS$OUT_Plots[[3]])
  } else{
    Pers.POST.RUN_RESULTS$OUT_Plots[[3]]
  }
}


```
